//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarhouseWebServiceClient.serviceRfrnce {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="serviceRfrnce.WarehouseSoap")]
    public interface WarehouseSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateOrder(string date, string name, string surname, string address, string articleCode, int articleAmount, string deliveryWay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindAvailableArticles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FindAvailableArticles();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WarehouseSoapChannel : WarhouseWebServiceClient.serviceRfrnce.WarehouseSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WarehouseSoapClient : System.ServiceModel.ClientBase<WarhouseWebServiceClient.serviceRfrnce.WarehouseSoap>, WarhouseWebServiceClient.serviceRfrnce.WarehouseSoap {
        
        public WarehouseSoapClient() {
        }
        
        public WarehouseSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WarehouseSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WarehouseSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WarehouseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateOrder(string date, string name, string surname, string address, string articleCode, int articleAmount, string deliveryWay) {
            return base.Channel.CreateOrder(date, name, surname, address, articleCode, articleAmount, deliveryWay);
        }
        
        public System.Data.DataSet FindAvailableArticles() {
            return base.Channel.FindAvailableArticles();
        }
    }
}
